ALTER TABLE FLOWER.T_FORECAST_REPORT ADD (CLICK_CNT  NUMBER DEFAULT 0);

ALTER TABLE FLOWER.T_BBS ADD (CLICK_CNT  NUMBER  DEFAULT 0);


CREATE TABLE FLOWER.T_DEADLINE
(
  DEADLINE_DATE    NUMBER (2) DEFAULT 27 NOT NULL 
);


COMMENT ON TABLE FLOWER.T_DEADLINE IS '마감관리';

COMMENT ON COLUMN FLOWER.T_DEADLINE.DEADLINE_DATE IS '마감일자';

  
INSERT INTO T_DEADLINE VALUES(27);


COMMIT;